### ISSUE TITLE
Android ArrayIndexOutOfBoundsException and AbsListViewRecycleBin.addScrapView

### ISSUE THREAD

**Issue by ipetu** [mrmans0n/smart-adapters#21]
Android ArrayIndexOutOfBoundsException and AbsListViewRecycleBin.addScrapView

java.lang.ArrayIndexOutOfBoundsException: length=2; index=894640594

Mapper.viewTypeFromViewClass(builder.viewType(object, position, mapper))

**Comment by ApofisXII** [comment]
+1!

**Comment by mrmans0n** [comment]
Is the same model class used for rendering multiple views? If so, allowsMultimapping should be returning true.

**Comment by ApofisXII** [comment]
I have already added it (it was specified in your documentation) but I had no luck.
Anyway, I have found a way in order to fix it in your files.
In the file "MultiAdapter.java" you need to edit the "getViewTypeCount()" function in order to return always: 1.
`@Override
public int getViewTypeCount() {
        return 1;
        //return mapper.viewSize();
    }`

This has fixed the problem in every ListView.

**Comment by ipetu** [comment]
mapper class  
   public static int viewTypeFromViewClass(Class<? extends BindableLayout> viewClass) {
        return viewClass.getCanonicalName().hashCode();
    }

 if (viewClass.getCanonicalName().hashCode()) value is positive number

baseApdater method getItemViewType() value  > getViewTypeCount() 
crash
