### ISSUE TITLE
BindableLayoutBuilder depending on position

### ISSUE THREAD

**Issue by nitrico** [mrmans0n/smart-adapters#3]
Is it possible to implement a BindableLayoutBuilder where the view class of an item depends on the item position in the adapter instead of its data?

I tried to return different layout id's when overriding BindableLayout.getLayoutId() but it didn't work (due to viewholders' recycling, I guess) and can't find the way to get the position from the BindableLayoutBuilder.

Thanks for the lib, so useful :)

**Comment by mrmans0n** [comment]
I will include the position in the builder interface in a next version, as it is a good fit. For the time being, a BindableLayout view has the position in the bind method so you could use that.

**Comment by nitrico** [comment]
That would be nice. Thank you.

**Comment by mrmans0n** [comment]
I have been able to look at the code and I've seen why the position was not included as part of the BindableLayoutBuilder. In the RecyclerView version you don't know the position up until binding time, and that's why it's passed to the bind(...) method in BindableLayout instead of being in the builder. 

I can't think of a way to circumvent this, so it's a tradeoff I had to make to make the library compatible with the old-school *Adapter classes and the RecyclerView adapters.
